### PR TITLE
Chrome/Firefox bookmark Import [WIP]

### PR DESCRIPTION
**Pull request by itsmehemant123**
This PR adds the ability to let users import the bookmarks from Chrome and Firefox.

Work in progress.

Copied over from https://github.com/n1try/anchr/issues/2

- [x] Looks like you broke the table. Table header as well as description- and date column is gone (see http://prntscr.com/i4iezf)
- [ ] The import-related UI is too prominent. Instead of the whole drag & drop thing, I'd rather add a small icon + text (analogously to the + New button in the left bar), which directly opens a file picker. Roughly like this: http://prntscr.com/i4ii4m. You don't necessarily need to add a progress indicator in my opinion.
- [ ] Auto-reload collections after import is complete, so that the user gets feedback on success and immediately can see his bookmarks.
- [ ] I'd suggest to rather use [bookmarks-parser](https://www.npmjs.com/package/bookmarks-parser) (instead of [bookmark-parser](https://www.npmjs.com/package/bookmark-parser)) since it has fewer dependencies and doesn't require Python and stuff for compilation (which makes it easier to be installed especially on Windows)
- [ ] As you said, correctly handle corner cases and possible errors
- [x] Please also remove this comment: http://prntscr.com/i4ilhf

### CODE REVIEW

**Comment by itsmehemant123** [comment]
@n1try can you confirm if the current master branch works like anchr.io? I still get the table issues though I'm on the master branch.

Likewise, https://github.com/n1try/anchr/blob/master/public/app/views/collection.html#L1 is where that comment crept in, which doesn't appear in anchr.io .

**Comment by n1try** [comment]
@itsmehemant123 You were right, there was a discrepancy between `master` and was is currently deployed on anchr.io. I fixed that with commit https://github.com/n1try/anchr/commit/8179e7488a3165e7e329aa332a138e0ae229e750. Sorry for the inconveniences.

**Comment by n1try** [comment]
Any news on this?

**Comment by itsmehemant123** [comment]
I got caught up with school work, will get back to this

**Pull request closed without merging**
